---
title: "2018 Diurnal profile variability"
author: "Yujie Xu"
date: "8/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/code/im3-wrf/")
```

The following plot examines the average heat emission across finer grid cells for different days in each month.

```{r checkDiurnalVariabilityByDay, fig.width=13, fig.height=8}
library("dplyr")
library("plotly")
library("dygraphs")

diurnal.stats <- readr::read_csv("diurnal_profile_agg_over_finer.csv")

diurnal.mean <- diurnal.stats %>%
  dplyr::filter(unit == "W/m2") %>%
  tidyr::separate(`Date`, into=c("month", "day"), sep="/") %>%
  {.}

p <- diurnal.mean %>%
  dplyr::mutate(Hour = as.numeric(Hour)) %>%
  dplyr::mutate(day.of.week = lubridate::wday(sprintf("2018-%s-%s", month, day), label = TRUE)) %>%
  ggplot2::ggplot(ggplot2::aes(x = Hour, y=mean, group=day, color=day.of.week)) +
  ggplot2::geom_line(size=0.2) +
  ## ggplot2::ylab("Grid hourly heat emission (W/m2)") +
  ggplot2::scale_color_brewer(palette = "Set3") +
  ggplot2::facet_grid(variable~month, scales = "free_y") +
  ggplot2::theme(legend.position = "bottom")
plotly::ggplotly(p)
```

Temperature profile

```{r weatherProfile, fig.width=10, fig.height=3}
df.weather <- readr::read_csv("weather_2018.csv")

df.weather.avg <- df.weather %>%
  tidyr::gather(variable, value, DryBulb.C:`WindSpd.m/s`) %>%
  dplyr::group_by(month, day, hour, variable) %>%
  dplyr::summarise(value = mean(value)) %>%
  dplyr::ungroup() %>%
  {.}

df.weather.avg <- df.weather.avg %>%
  dplyr::mutate(timestamp = sprintf("2018-%02d-%02d %02d:00:00", month, day, hour)) %>%
  dplyr::mutate(timestamp.pox = as.POSIXct(timestamp, format="%Y-%m-%d %H:%M:%S")) %>%
  {.}

to.plot.temperature <- df.weather.avg %>%
  dplyr::filter(variable == "DryBulb.C") %>%
  dplyr::filter(!is.na(timestamp.pox)) %>%
  {.}

dygraphs::dygraph(xts::xts(to.plot.temperature$value, order.by=to.plot.temperature$timestamp.pox),
                  main="outdoor Temperature") %>%
  dyRangeSelector()
```
Non-surface building heat emission

```{r compileXTS}
spatial.suf = "_finer"
df.heat.comp = readr::read_csv(sprintf("diurnal_profile_agg_over%s.csv", spatial.suf))

to.plot.heat.comp <- df.heat.comp %>%
  dplyr::filter(unit == "W/m2") %>%
  dplyr::mutate(Hour = as.numeric(Hour) - 1) %>%
  dplyr::mutate(timestamp = sprintf("2018/%s %02d:00:00", Date, Hour)) %>%
  dplyr::mutate(timestamp.pox = as.POSIXct(timestamp, format="%Y/%m/%d %H:%M:%S")) %>%
  dplyr::filter(!is.na(timestamp.pox)) %>%
  dplyr::select(variable, timestamp.pox, mean) %>%
  {.}

heat.surf = to.plot.heat.comp %>%
  dplyr::filter(variable == "emission.surf") %>%
  dplyr::select(timestamp.pox, mean) %>%
  {.}
heat.surf.xts = xts::xts(heat.surf$mean, order.by=heat.surf$timestamp.pox)
heat.rej = to.plot.heat.comp %>%
  dplyr::filter(variable == "emission.rej") %>%
  dplyr::select(timestamp.pox, mean) %>%
  {.}
heat.rej.xts = xts::xts(heat.rej$mean, order.by=heat.rej$timestamp.pox)
heat.exfiltration = to.plot.heat.comp %>%
  dplyr::filter(variable == "emission.exfiltration") %>%
  dplyr::select(timestamp.pox, mean) %>%
  {.}
heat.exfiltration.xts = xts::xts(heat.exfiltration$mean, order.by=heat.exfiltration$timestamp.pox)
heat.exhaust = to.plot.heat.comp %>%
  dplyr::filter(variable == "emission.exhaust") %>%
  dplyr::select(timestamp.pox, mean) %>%
  {.}
heat.exhaust.xts = xts::xts(heat.exhaust$mean, order.by=heat.exhaust$timestamp.pox)
heat.ref = to.plot.heat.comp %>%
  dplyr::filter(variable == "emission.ref") %>%
  dplyr::select(timestamp.pox, mean) %>%
  {.}
heat.ref.xts = xts::xts(heat.ref$mean, order.by=heat.ref$timestamp.pox)
```

```{r heatEmissionNonSurf, fig.width=10, fig.height=3}
dygraphs::dygraph(cbind(heat.rej.xts, heat.exhaust.xts, heat.exfiltration.xts, heat.ref.xts),
                  main="Building Heat Emission (excluding surface emission)") %>%
  dygraphs::dyOptions(colors = RColorBrewer::brewer.pal(4, "Set2"))
```

Total building surface heat emission

```{r heatEmissionComp, fig.width=10, fig.show="hold", fig.height=3}
dygraphs::dygraph(heat.surf.xts,
                  main="Building Surface Heat Emission") %>%
  dyRangeSelector()
```

Total heat emission profile

```{r heatEmission, fig.width=10, fig.height=3}
df.heat = readr::read_csv(sprintf("diurnal_profile_totalHeat_agg_over%s.csv", spatial.suf))

to.plot.heat <- df.heat %>%
  dplyr::filter(unit == "W/m2") %>%
  dplyr::mutate(Hour = as.numeric(Hour) - 1) %>%
  dplyr::mutate(timestamp = sprintf("2018/%s %02d:00:00", Date, Hour)) %>%
  dplyr::mutate(timestamp.pox = as.POSIXct(timestamp, format="%Y/%m/%d %H:%M:%S")) %>%
  dplyr::filter(!is.na(timestamp.pox)) %>%
  dplyr::select(timestamp.pox, mean) %>%
  {.}

dygraphs::dygraph(xts::xts(to.plot.heat$mean, order.by=to.plot.heat$timestamp.pox),
                  main="Building Total Heat Emission") %>%
dyRangeSelector()
```

correlation between heat emission and dry-bulb temperature

```{r correlation, fig.width = 12}
mean.heat <- df.heat %>%
  dplyr::filter(unit == "W/m2") %>%
  dplyr::rename(hour=Hour) %>%
  tidyr::separate(`Date`, into=c("month", "day"), sep = "/") %>%
  dplyr::mutate_at(vars(month, day, hour), as.numeric) %>%
  dplyr::select(month:hour, mean) %>%
  {.}

to.plot.correlation <- df.weather.avg %>%
  dplyr::select(month:value) %>%
  tidyr::spread(variable, value) %>%
  dplyr::inner_join(mean.heat, by=c("month", "day", "hour")) %>%
  {.}

to.plot.correlation %>%
  dplyr::group_by(month, day) %>%
  dplyr::summarise(DryBulb.C = mean(DryBulb.C), mean=mean(mean)) %>%
  ggplot2::ggplot(ggplot2::aes(x = DryBulb.C, y=mean)) +
  ggplot2::geom_point(size=0.5) +
  ggpmisc::stat_poly_line() +
  ggpmisc::stat_poly_eq(aes(label = paste(after_stat(eq.label),
                                          after_stat(rr.label), sep = "*\", \"*"))) +
  ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  ggplot2::ylab("Average grid heat emission (W/m2)") +
  ggplot2::ggtitle("Daily total heat emission vs\noutdoor temperature") +
  ggplot2::theme(text = ggplot2::element_text(size = 20))
```

```{r correlationComp, fig.show="hold", out.width="50%", fig.width=6, fig.height=4}
mean.heat.comp <- df.heat.comp %>%
  dplyr::filter(unit == "W/m2") %>%
  dplyr::rename(hour=Hour) %>%
  tidyr::separate(`Date`, into=c("month", "day"), sep = "/") %>%
  dplyr::mutate_at(vars(month, day, hour), as.numeric) %>%
  dplyr::select(month:hour, variable, mean) %>%
  {.}

to.plot.correlation.comp <- df.weather.avg %>%
  dplyr::select(month:value) %>%
  tidyr::spread(variable, value) %>%
  dplyr::right_join(mean.heat.comp, by=c("month", "day", "hour")) %>%
  {.}

heat.source = c("emission.exfiltration", "emission.exhaust", "emission.ref", "emission.rej", "emission.surf")
heat.label = c("exfiltration", "exhaust", "relief air", "HVAC rejection", "building surface")

for (i in seq_along(heat.source)) {
  p <- to.plot.correlation.comp %>%
    dplyr::filter(variable == heat.source[[i]]) %>%
    dplyr::group_by(month, day, variable) %>%
    dplyr::summarise(DryBulb.C = mean(DryBulb.C), mean=mean(mean)) %>%
    ggplot2::ggplot(ggplot2::aes(x = DryBulb.C, y=mean)) +
    ggplot2::geom_point(size=0.5) +
    ggpmisc::stat_poly_line() +
    ggpmisc::stat_poly_eq(aes(label = paste(after_stat(eq.label),
                                            after_stat(rr.label), sep = "*\", \"*"))) +
    ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
    ggplot2::xlab("DryBulb Temperature") +
    ggplot2::ylab("Average grid heat emission (W/m2)") +
    ## ggplot2::ggtitle(sprintf("Correlation between daily average temperature\nand daily average %s heat emission",
    ##                          heat.label[[i]])) +
    ggplot2::ggtitle(sprintf("Daily %s heat emission vs\noutdoor temperature", heat.label[[i]])) +
    ggplot2::theme(text = ggplot2::element_text(size = 20),
                   axis.title = ggplot2::element_text(size = 15))
  print(p)
}
```
