---
title: "Figures in the paper"
author: "Yujie Xu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/meta_repo/xu_etal_2022_tbd/")
```

# Figures
## Figure 3 Building type composition of the compiled building stock data
```{r figure3}
library("dplyr")

type.recode <- readr::read_csv("input_data/building_type_recode.csv") %>%
    dplyr::select(-count) %>%
    {.}

size.type.summary <- readr::read_csv("intermediate_data/compiled_LA_size_type_summary.csv")

to.plot.pie <- size.type.summary %>%
    dplyr::left_join(type.recode, by=c("GeneralUseType", "SpecificUseType")) %>%
    dplyr::group_by(`remap EP ref building`) %>%
    dplyr::summarise_at(vars(total.building.size.mil.sqft, building.size.percent), sum) %>%
    dplyr::ungroup() %>%
    dplyr::arrange(desc(building.size.percent)) %>%
    dplyr::mutate(type = ifelse(building.size.percent > 0.03, `remap EP ref building`, "other")) %>%
    dplyr::group_by(type) %>%
    dplyr::summarise_at(vars(total.building.size.mil.sqft, building.size.percent), sum) %>%
    dplyr::ungroup() %>%
    dplyr::arrange(desc(building.size.percent)) %>%
    {.}

to.plot.pie <- to.plot.pie %>%
    dplyr::mutate(type = ifelse(type %in% c("single-family", "multi-family"), paste("residential, ", type), type)) %>%
    arrange(desc(type)) %>%
    mutate(prop = building.size.percent / sum(to.plot.pie$building.size.percent) *100) %>%
    mutate(ypos = cumsum(prop)- 0.5*prop ) %>%
    {.}

ggplot2::ggplot(to.plot.pie, ggplot2::aes(x="", y=prop, fill=type)) +
    ggplot2::geom_bar(stat="identity", width=1, color="white") +
    ggplot2::coord_polar("y", start=0) +
    ggplot2::theme_void() +
    ggplot2::theme(legend.position="none") +
    ggrepel::geom_text_repel(ggplot2::aes(y = ypos, label = type), color = "black", nudge_x = 0.7) +
    ggplot2::scale_fill_brewer(palette="Set1") +
    ggplot2::theme()
ggplot2::ggsave("figures/building_type_pie.png", width = 4, height = 4, units = "in", dpi = 600)
```

Figure 4

```{r figure4, eval=TRUE}
if (!file.exists("intermediate_data/df_la_building_year_size.csv")) {
  ## this is before joining to grid
  df.la.building <- sf::st_read("intermediate_data/compiled_LA_building.geojson")
  df.la.building.remove.geo <- df.la.building
  sf::st_geometry(df.la.building.remove.geo) <- NULL
  df.la.building.remove.geo <- df.la.building.remove.geo %>%
    tibble::as_tibble() %>%
    dplyr::select(OBJECTID, EffectiveYearBuilt, SQFTmain, GeneralUseType) %>%
    {.}
  df.la.building.remove.geo %>%
    readr::write_csv("intermediate_data/df_la_building_year_size.csv")
} else {
  df.la.building.remove.geo <-
    readr::read_csv("intermediate_data/df_la_building_year_size.csv")
}

## top four GeneralUseType
## GeneralUseType total.building.size
## <fct>                        <dbl>
## 1 Residential              4078.    
## 2 Industrial                809.    
## 3 Commercial                730.    
## 4 Institutional             124.    
## 5 Recreational               21.2   
df.la.building.remove.geo %>%
  dplyr::group_by(GeneralUseType) %>%
  dplyr::summarise(total.building.size = sum(SQFTmain) * 1e-6) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(desc(total.building.size)) %>%
  dplyr::slice(1:5) %>%
  knitr::kable()

data.median <- df.la.building.remove.geo %>%
  dplyr::filter(GeneralUseType %in% c("Residential", "Industrial", "Commercial", "Institutional")) %>%
  dplyr::group_by(GeneralUseType) %>%
  dplyr::summarise(EffectiveYearBuilt = median(EffectiveYearBuilt)) %>%
  dplyr::ungroup()

df.la.building.remove.geo %>%
  dplyr::filter(GeneralUseType %in% c("Residential", "Industrial", "Commercial", "Institutional")) %>%
  ggplot2::ggplot() +
  ggplot2::geom_violin(ggplot2::aes(x = GeneralUseType, y = EffectiveYearBuilt),
                        position = ggplot2::position_dodge(width = 0.5)) +
  ggplot2::geom_boxplot(ggplot2::aes(x = GeneralUseType, y = EffectiveYearBuilt),
                        width = 0.2, position = ggplot2::position_dodge(width = 0.5), outlier.size = 0.5) +
  ggplot2::geom_hline(yintercept = 1980, linetype = "dashed") +
  ggplot2::geom_text(ggplot2::aes(x = GeneralUseType, y = EffectiveYearBuilt, label = EffectiveYearBuilt),
                      data = data.median, size = 2, vjust = -0.5) +
  ggplot2::ylab("Year Built (EffectiveYearBuilt)") +
  ggplot2::theme()
ggplot2::ggsave("figures/built_year_by_main_GeneralUseType.png", width = 4, height = 4, units = "in", dpi = 600)
```

Figure 5

```{r figure5, eval=TRUE}
grid.path = "input_data/M02_EnergyPlus_Forcing_Historical_LowRes/meta"
df.grid <- sf::st_read(sprintf("%s/wrf-grids-origin.geojson", grid.path))
la.boundary <- sf::read_sf("input_data/domain/la-county-boundary.geojson")
df.grid %>%
   ggplot2::ggplot() +
   ggplot2::geom_sf(size = 0.2) +
   ggplot2::ggtitle("wrf grid") +
   ggplot2::geom_sf(data = la.boundary, fill=NA, color = "red") +
   ggplot2::theme()
```

Figure 6

```{r figure6, fig.width=10, eval=TRUE}

if (!file.exists("intermediate_data/weather_2018.csv")) {
  ## for july data
  ## climate.folder = "input_data/M02_EnergyPlus_Forcing_Historical_LowRes"
  ## for 2018 annual
  climate.folder = "input_data/annual_WRF/M02_EnergyPlus_Forcing_Historical_LowRes_ann_2018"
  files = list.files(path=sprintf("%s/wrf_epw/", climate.folder), pattern = "*.epw")

  source("read_epw.R")

  result <- lapply(files, function(f) {
    print(f)
    ## skip 8 non-data rows
    df = read.epw(sprintf("%s/wrf_epw/%s", climate.folder, f)) %>%
      dplyr::mutate(filename = f) %>%
      {.}
  })

  df.all.weather <- result %>%
    dplyr::bind_rows() %>%
    dplyr::mutate(cell.id = as.numeric(gsub(".epw", "", filename))) %>%
    {.}
  df.cell.with.building <- readr::read_csv("intermediate_data/summary/building_type_vintage_count_per_grid.csv") %>%
    dplyr::distinct(id)

  df.weather.with.cell <- df.all.weather %>%
    dplyr::inner_join(df.cell.with.building, by=c("cell.id"="id"))

  df.weather.with.cell %>%
    readr::write_csv("intermediate_data/weather_2018.csv")
} else {
  df.weather.with.cell <-
    readr::read_csv("intermediate_data/weather_2018.csv")
}

df.weather.with.cell %>%
  dplyr::mutate(cell.id = factor(cell.id)) %>%
  dplyr::filter((month == 6 & day > 25) | (month == 7) | (month == 8 & day < 7)) %>%
  dplyr::select(cell.id, month:minute, DryBulb.C, RelHum.percent, `WindSpd.m/s`
                ) %>%
  dplyr::mutate(timestamp = sprintf("2018-%02d-%02d %02d:%02d:00", month, day, hour, minute)) %>%
  dplyr::mutate(timestamp.pox = as.POSIXct(timestamp)) %>%
  tidyr::gather(variable, value, DryBulb.C:`WindSpd.m/s`) %>%
  dplyr::mutate_at(vars(variable), recode, "DryBulb.C"="Dry Bulb Temperature (C)",
                   "RelHum.percent" = "Relative Humidity (%)",
                    "WindSpd.m/s"="Wind Speed (m/s)") %>%
  ggplot2::ggplot(ggplot2::aes(x=timestamp.pox, y=value, color=cell.id, group=cell.id)) +
  ggplot2::geom_line(size = 0.2) +
  ggplot2::facet_wrap(.~variable, ncol=1, scales = "free_y") +
  ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-06 00:00:00"), linetype = "dashed") +
  ggplot2::xlab("Time") +
  ggplot2::ylab("") +
  ggplot2::theme()
ggplot2::ggsave("figures/compiled_epw_weather.png", width = 10, height = 5, units = "in", dpi = 600)
```

Figure 7

```{r figure7, eval=TRUE}
## to be added
if (!file.exists("intermediate_data/resstock_la.csv")) {
  df.restock = readr::read_tsv("input_data/resstock/metadata.tsv")
  df.restock.la <- df.restock %>%
    dplyr::filter(in.resstock_county_id == "CA, Los Angeles County") %>%
    dplyr::filter(stringr::str_detect(in.geometry_building_type_recs, "-Family")) %>%
    dplyr::select(bldg_id,
                  in.county,
                  out.electricity.total.energy_consumption_intensity,
                  out.natural_gas.total.energy_consumption_intensity,
                  in.geometry_building_type_recs,
                  in.vintage_acs,
                  in.weather_file_TMY3) %>%
    dplyr::rename(elec = out.electricity.total.energy_consumption_intensity,
                  gas = out.natural_gas.total.energy_consumption_intensity) %>%
    tidyr::separate(in.geometry_building_type_recs, into=c("type", "suf", "suf2"), sep="-") %>%
    dplyr::select(-suf, -suf2) %>%
    dplyr::mutate(type = sprintf("%sFamily", type)) %>%
    {.}
  df.restock.la %>%
    readr::write_csv("intermediate_data/resstock_la.csv")
} else {
  df.restock.la <-
    readr::read_csv("intermediate_data/resstock_la.csv")
}

df.resstock.mod.vintage <- df.restock.la %>%
  dplyr::rename(vintage = in.vintage_acs) %>%
  {.}

df.res.to.plot <- df.resstock.mod.vintage %>%
  dplyr::mutate(vintage = case_when(vintage == "2010s" ~ "2013",
                                    vintage %in% c("2000-09", "1980-99") ~ "2004",
                                    TRUE ~ "pre 1980")) %>%
  {.}

source("compile_sim_result.R")

prototype.area <- readr::read_csv("input_data/prototype_bldg_area.csv") %>%
  dplyr::mutate(idf.kw = gsub(".idf", "", idf.name, fixed=TRUE)) %>%
  dplyr::mutate(idf.kw = gsub(".", "_", idf.kw, fixed=TRUE)) %>%
  {.}

if (!file.exists("intermediate_data/result_G0600370_compile_elec_gas.csv")) {
  result.G0600370.compile.elec.gas <- compile.sim.result.elec.gas("intermediate_data/EP_output/using_G0600370", prototype.area) %>%
    dplyr::mutate(vintage = ifelse(is.na(c), b, c)) %>%
    dplyr::mutate(vintage = ifelse(vintage == "LA", "-", vintage)) %>%
    dplyr::mutate(vintage = ifelse(vintage == "1980", "pre 1980", vintage)) %>%
    dplyr::select(vintage, type, variable, EUI.GJ.per.m2) %>%
    na.omit() %>%
    dplyr::mutate(source = "this study") %>%
    {.}
  result.G0600370.compile.elec.gas %>%
    readr::write_csv("intermediate_data/result_G0600370_compile_elec_gas.csv")
} else {
  result.G0600370.compile.elec.gas <-
    readr::read_csv("intermediate_data/result_G0600370_compile_elec_gas.csv")
}

result.G0600370.compile.elec.gas.res <- result.G0600370.compile.elec.gas %>%
  dplyr::filter(type %in% c("SingleFamily", "MultiFamily")) %>%
  {.}

result.G0600370.compile.elec.gas.res.total <- result.G0600370.compile.elec.gas.res %>%
  dplyr::group_by(vintage, type) %>%
  dplyr::summarise(EUI.GJ.per.m2 = sum(EUI.GJ.per.m2),
                   source = first(source)) %>%
  dplyr::ungroup() %>%
  {.}

get.plot.df.cmp.res.com.stock.total <- function(df.res.com, source.label, df.sim) {
  df.res.com %>%
    ## convert kwh/sqft to GJ/m2
    dplyr::mutate(EUI.GJ.per.m2 = (elec + gas) * 0.0036 / 0.092903) %>%
    dplyr::select(vintage, type, EUI.GJ.per.m2) %>%
    dplyr::mutate(source = source.label) %>%
    dplyr::bind_rows(df.sim) %>%
    dplyr::group_by(type, vintage) %>%
    dplyr::filter(length(unique(source)) > 1) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(vintage = factor(vintage, levels = c("pre 1980", "2004", "2013"))) %>%
    {.}
}

df.res.to.plot <- df.res.to.plot %>%
  get.plot.df.cmp.res.com.stock.total(source.label = "ResStock", df.sim = result.G0600370.compile.elec.gas.res.total) %>%
  {.}

df.res.to.plot %>%
  dplyr::filter(source == "ResStock") %>%
  ggplot2::ggplot() +
  ggplot2::geom_boxplot(ggplot2::aes(x = type, y = EUI.GJ.per.m2, fill = source), outlier.size = 0.2, lwd = 0.2) +
  ggplot2::geom_point(ggplot2::aes(x = type, y = EUI.GJ.per.m2), color = "#00BFC4",
                      data = df.res.to.plot %>% filter(source == "this study")) +
  ggplot2::facet_wrap(vintage~., nrow = 1) +
  ggplot2::ylab("GJ/m2") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90), legend.position = "bottom")
ggplot2::ggsave("figures/cmp_resstock_this_study.png", width = 5, height = 6, units = "in", dpi = 600)

## only single family, used in a slide
df.res.to.plot %>%
  dplyr::filter(source == "ResStock") %>%
  dplyr::filter(type == "SingleFamily") %>%
  ggplot2::ggplot() +
  ggplot2::geom_boxplot(ggplot2::aes(x = vintage, y = EUI.GJ.per.m2, fill = source), outlier.size = 0.2, lwd = 0.2) +
  ggplot2::geom_point(ggplot2::aes(x = vintage, y = EUI.GJ.per.m2), color = "#00BFC4",
                      data = df.res.to.plot %>% filter(source == "this study", type == "SingleFamily")) +
  ggplot2::ylab("GJ/m2") +
  ggplot2::coord_flip() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90), legend.position = "bottom")
ggplot2::ggsave("figures/cmp_resstock_this_study_singleFamily.png", width = 6, height = 3, units = "in", dpi = 600)
```

Figure 8

```{r figure8, eval=TRUE}
if (!file.exists("intermediate_data/comstock_la.csv")) {
  df.comstock = readr::read_tsv("input_data/comstock/metadata.tsv")
  df.comstock.la <- df.comstock %>%
    dplyr::filter(in.state_abbreviation == "CA") %>%
    dplyr::filter(in.resstock_county_id == "CA, Los Angeles County") %>%
    dplyr::select(bldg_id,
                  in.county,
                  out.electricity.total.energy_consumption_intensity,
                  out.natural_gas.total.energy_consumption_intensity,
                  in.building_type,
                  in.energy_code_followed_during_original_building_construction,
                  in.weather_file_TMY3) %>%
    dplyr::rename(elec = out.electricity.total.energy_consumption_intensity,
                  gas = out.natural_gas.total.energy_consumption_intensity,
                  type = in.building_type) %>%
    dplyr::mutate(vintage = gsub("ComStock DEER ", "", in.energy_code_followed_during_original_building_construction)) %>%
    {.}
  df.comstock.la %>%
    readr::write_csv("intermediate_data/comstock_la.csv")
} else {
  df.comstock.la <-
    readr::read_csv("intermediate_data/comstock_la.csv")
}

df.com.to.plot <- df.comstock.la %>%
  dplyr::mutate(vintage = case_when(vintage %in% c("2011", "2014", "2015", "2017") ~ "2013",
                                    vintage %in% c("1985", "1996", "2003", "2007") ~ "2004",
                                    TRUE ~ "pre 1980")) %>%
  dplyr::mutate(vintage = factor(vintage, levels = c("pre 1980", "2004", "2013"))) %>%
  {.}

get.plot.df.cmp.res.com.stock.total <- function(df.res.com, source.label, df.sim) {
  df.res.com %>%
    ## convert kwh/sqft to GJ/m2
    dplyr::mutate(EUI.GJ.per.m2 = (elec + gas) * 0.0036 / 0.092903) %>%
    dplyr::select(vintage, type, EUI.GJ.per.m2) %>%
    dplyr::mutate(source = source.label) %>%
    dplyr::bind_rows(df.sim) %>%
    dplyr::group_by(type, vintage) %>%
    dplyr::filter(length(unique(source)) > 1) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(vintage = factor(vintage, levels = c("pre 1980", "2004", "2013"))) %>%
    {.}
}

result.G0600370.compile.elec.gas.nonres.total <- result.G0600370.compile.elec.gas %>%
  dplyr::filter(!(type %in% c("SingleFamily", "MultiFamily"))) %>%
  dplyr::group_by(vintage, type) %>%
  dplyr::summarise(EUI.GJ.per.m2 = sum(EUI.GJ.per.m2),
                   source = first(source)) %>%
  dplyr::ungroup() %>%
  {.}

## read California Building Energy Benchmarking Program data
## https://www.energy.ca.gov/media/4640
df.benchmark <- readxl::read_excel("input_data/CECdata/2018_Download_20220826_ADA.xlsx", skip = 2)

df.benchmark.la <- df.benchmark %>%
    dplyr::filter(`County from Geocoding` == "Los Angeles") %>%
    dplyr::select(`Property Id`, `Property Name`, `Year Built`, `Property GFA - Calculated (Buildings) (ft²)`,
                  `Primary Property Type - Portfolio Manager-Calculated`,
                  `Electricity Use - Grid Purchase (kBtu)`,
                  `Electricity Use – Generated from Onsite Renewable Systems and Used Onsite (kBtu)`,
                  `Natural Gas Use (kBtu)`
                  ) %>%
    dplyr::rename(elec.grid.purchase = `Electricity Use - Grid Purchase (kBtu)`,
                  elec.onsite = `Electricity Use – Generated from Onsite Renewable Systems and Used Onsite (kBtu)`) %>%
    dplyr::mutate(elec.kbtu = case_when(is.na(elec.onsite) ~ elec.grid.purchase,
                                        is.na(elec.grid.purchase) ~ elec.onsite,
                                        TRUE ~ elec.grid.purchase + elec.onsite),
                  gas.kbtu = `Natural Gas Use (kBtu)`) %>%
    dplyr::mutate(total.kbtu = case_when(is.na(elec.kbtu) ~ gas.kbtu,
                                         is.na(gas.kbtu) ~ elec.kbtu,
                                         TRUE ~ elec.kbtu + gas.kbtu)) %>%
    dplyr::select(`Property Id`, `Property Name`, `Year Built`, `Property GFA - Calculated (Buildings) (ft²)`,
                  `Primary Property Type - Portfolio Manager-Calculated`, elec.kbtu, gas.kbtu, total.kbtu) %>%
    dplyr::mutate(vintage = case_when(`Year Built` < 1980 ~ "pre 1980",
                                       `Year Built` < 2009 ~ "2004",
                                      TRUE ~ "2013")) %>%
    dplyr::mutate(vintage = factor(vintage, levels = c("pre 1980", "2004", "2013"))) %>%
    {.}

## df.benchmark.la %>%
##     readr::write_csv("intermediate_data/benchmark_la.csv")

## df.benchmark.la %>%
##     distinct(`Primary Property Type - Portfolio Manager-Calculated`) %>%
##     readr::write_csv("intermediate_data/benchmark_building_type.csv")

df.benchmark.recode <- readr::read_csv("input_data/benchmark_building_type_recode.csv") %>%
    na.omit()

df.benchmark.stat.la <- df.benchmark.la %>%
    dplyr::inner_join(df.benchmark.recode, by="Primary Property Type - Portfolio Manager-Calculated") %>%
    dplyr::rename(gsf.sqft = `Property GFA - Calculated (Buildings) (ft²)`) %>%
    dplyr::rename(type = remap) %>%
    dplyr::mutate(type = case_when(type == "hotel" ~ ifelse(gsf.sqft >= 64583.46, "LargeHotel", "SmallHotel"),
                                   type == "office" ~ case_when(gsf.sqft > 100000 ~ "LargeOffice",
                                                                gsf.sqft < 2500 ~ "SmallOffice",
                                                                TRUE ~ "MediumOffice"),
                                   TRUE ~ type)) %>%
    dplyr::mutate(`EUI.GJ.per.m2` = (total.kbtu / 948) / (gsf.sqft * 0.092903)) %>%
    dplyr::filter(!is.na(`EUI.GJ.per.m2`)) %>%
    dplyr::group_by(type, vintage) %>%
    dplyr::summarise_at(vars(EUI.GJ.per.m2),
                        tibble::lst(Q1 = ~quantile(., probs=0.25), median, Q3 = ~quantile(., probs=0.75))) %>%
    dplyr::ungroup() %>%
    dplyr::filter(!(type %in% c("supermarket", "college", "religious", "Outpatient", "RetailStripmall", "QuickServiceRestaurant"))) %>%
    dplyr::mutate(vintage = factor(vintage, levels = c("pre 1980", "2004", "2013"))) %>%
    {.}

df.com.to.plot <- df.com.to.plot %>%
  dplyr::filter(type != "SecondarySchool") %>%
  get.plot.df.cmp.res.com.stock.total(source.label = "ComStock", df.sim = result.G0600370.compile.elec.gas.nonres.total) %>%
  {.}

benchmark.color = "#C77CFF"
df.com.to.plot %>%
  dplyr::filter(source == "ComStock") %>%
  ggplot2::ggplot() +
  ggplot2::geom_boxplot(ggplot2::aes(x = type, y = EUI.GJ.per.m2, fill = source),
                        outlier.size = 0.2, lwd = 0.2, show.legend = FALSE) +
  ggplot2::geom_point(ggplot2::aes(x = type, y = EUI.GJ.per.m2), color = "#00BFC4",
                      data = df.com.to.plot %>% filter(source == "this study")) +
  ggplot2::geom_errorbar(ggplot2::aes(x = type, ymin = Q1, ymax = Q3),
                         data = df.benchmark.stat.la, color = benchmark.color) +
  ggplot2::geom_point(ggplot2::aes(x = type, y = median), data = df.benchmark.stat.la, color = benchmark.color, shape = 4) +
  ggplot2::facet_wrap(vintage~., nrow = 1) +
  ggplot2::ylab("GJ/m2") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90))
ggplot2::ggsave("figures/cmp_comstock_this_study.png", width = 8, height = 6, units = "in", dpi = 600)
```

Figure 9

```{r figure9, out.width="50%", fig.show="hold", eval=TRUE}
library("tmap")
library("ggpmisc")

la.nb.geo <- sf::st_read("input_data/EnergyAtlas/neighborhoods/neighborhoods.shp")

la.nb.geo.4326 <- sf::st_transform(la.nb.geo, crs=4326)

la.nb.geo.4326.id <- la.nb.geo.4326 %>%
  dplyr::select(neighborho)

plot.map.cmp <- function(df, fill.col, palette.name, title.str, output.name) {
  p <- df %>%
    dplyr::inner_join(la.nb.geo.4326.id, by=c("id.num"="neighborho")) %>%
    sf::st_as_sf() %>%
    tm_shape() +
    tm_polygons(fill.col, n=10, style="quantile", palette=palette.name) +
    tm_facets(by="source") +
    tm_layout(main.title = title.str,
              legend.position=c("left", "bottom"), legend.outside=FALSE)
  print(p)
  tmap_save(p, output.name, height=5, dpi = 600)
}

plot.scatter.cmp <- function(df, title.str, output.name) {
  limit = max(max(df$`atlas 2016`, na.rm = TRUE), max(df$`simulation 2016`, na.rm = TRUE))
  p <- df %>%
    ggplot2::ggplot(ggplot2::aes(x=`atlas 2016`, y=`simulation 2016`)) +
    ggplot2::geom_point(size = 0.2) +
    ggpmisc::stat_poly_line(formula = y ~ 0 + x) +
    ggpmisc::stat_poly_eq(formula = y ~ 0 + x, aes(label = paste(after_stat(eq.label),
                                                                 after_stat(rr.label), sep = "*\", \"*"))) +
    ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
    ggplot2::ggtitle(title.str) +
    ggplot2::coord_cartesian(x = c(0, limit), y = c(0, limit)) +
    ggplot2::theme()
  print(p)
  ggplot2::ggsave(output.name, width = 4, height = 4, dpi = 600)
}

cmp.energy.total <- readr::read_csv("neighborhood_usage_simulation_atlas_cmp_2016.csv")

cmp.total.by.fuel <- cmp.energy.total %>%
  ## kwh to TJ
  dplyr::mutate(usage = case_when(variable == "electricity" ~ usage * 0.0036 * 1e-3,
                                  variable == "gas" ~ usage * 0.10548 * 1e-3,
                                  variable == "total" ~ usage * 1.05506e-6 * 1e-3)) %>%
  dplyr::group_by(id.num, variable) %>%
  dplyr::filter(n() > 1) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(variable) %>%
  dplyr::group_split()

for (df.j in cmp.total.by.fuel) {
  fuel.j = df.j$variable[[1]]
  plot.map.cmp(df.j, fill.col="usage", palette.name="YlOrRd",
               title.str=sprintf(sprintf("%s (GBtu)", fuel.j)),
               output.name=sprintf("figures/cmp_neighbor_total_by_fuel_%s.png", fuel.j))
}

for (df.j in cmp.total.by.fuel) {
  fuel.j = df.j$variable[[1]]
  df.j %>%
    tidyr::spread(source, usage) %>%
    plot.scatter.cmp(sprintf("%s (GBtu) comparison", fuel.j),
                    sprintf("figures/scatter_neighbor_total_by_fuel_%s.png", fuel.j))
}
```

Figure 10-11

```{r figure10to11, out.width="50%", fig.show="hold", eval=TRUE}

source("read_energyAtlas.R")

df.energy.county.nb.remove.masked <- lapply(c("electricity", "gas", "total"), function(energy.type){
    read.energy.atlas(energy.type, remove.masked.data = TRUE) %>%
        dplyr::filter(id.type == "neighborhoods") %>%
        dplyr::select(id.num, usetype, usage, sqft) %>%
        dplyr::mutate(usage = as.numeric(usage)) %>%
        dplyr::mutate(variable = energy.type) %>%
        {.}
}) %>%
    dplyr::bind_rows() %>%
    {.}

df.remove.na <- df.energy.county.nb.remove.masked %>%
    dplyr::filter(!is.na(usage))

sim.by.nb.2016 <- readr::read_csv("intermediate_data/annual_sim_result_by_neighborhood_2016.csv")

nb.with.simulation.data <- sim.by.nb.2016 %>%
  dplyr::distinct(neighborho)

df.keep.data.with.sim <- df.remove.na %>%
    dplyr::mutate(id.num = as.numeric(id.num)) %>%
    dplyr::inner_join(nb.with.simulation.data, by=c("id.num"="neighborho")) %>%
    {.}

sim.by.nb.usetype.2016 <- sim.by.nb.2016 %>%
  dplyr::select(neighborho, usetype, building.area.m2, starts_with("energy")) %>%
  ## J to kwh
  dplyr::mutate(electricity = energy.elec * 2.77778e-7,
                ## J to therm
                gas = energy.gas * 9.48043e-9,
                ## J to btu
                total = energy.overall * 0.000947817) %>%
  dplyr::select(-starts_with("energy")) %>%
  dplyr::group_by(neighborho, usetype) %>%
  dplyr::summarise_if(is.numeric, sum) %>%
  dplyr::ungroup() %>%
  {.}

cmp.size <- df.keep.data.with.sim %>%
  dplyr::select(-usage) %>%
  dplyr::filter(variable == "total") %>%
  dplyr::select(-variable) %>%
  dplyr::mutate(building.area.m2 = sqft * 0.0929) %>%
  dplyr::select(-sqft) %>%
  dplyr::mutate(source = "atlas 2016") %>%
  dplyr::bind_rows(sim.by.nb.usetype.2016 %>%
                   dplyr::select(neighborho, usetype, building.area.m2) %>%
                   dplyr::rename(id.num = neighborho) %>%
                   dplyr::mutate(source = "simulation 2016") %>%
                   {.}) %>%
  dplyr::group_by(id.num, usetype) %>%
  dplyr::filter(n() == 2) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(id.num, usetype, source) %>%
  {.}

size.by.type <- cmp.size %>%
  dplyr::filter(usetype %in% c("single_family", "multi_family")) %>%
  dplyr::mutate(building.area.thousand.m2 = building.area.m2 * 1e-3) %>%
  dplyr::select(-building.area.m2) %>%
  dplyr::group_by(usetype) %>%
  dplyr::group_split()

## plot by each usetype
for (df.i in size.by.type) {
  type.i = df.i$usetype[[1]]
  ## print(type.i)
  plot.map.cmp(df.i, "building.area.thousand.m2", "Purples",
               sprintf("%s building size(thousand m2)", type.i),
               sprintf("figures/cmp_neighbor_bld_size_%s.png", type.i))
  df.i %>%
    tidyr::spread(source, building.area.thousand.m2) %>%
    plot.scatter.cmp(
      sprintf("%s building size scatter plot\n(thousand m2)", type.i),
      sprintf("figures/scatter_neighbor_bld_size_%s.png", type.i))
}
```

Figure 12-13

```{r figure12to13, out.width="50%", fig.show="hold", eval=TRUE}

cmp.energy <- readr::read_csv("neighborhood_usage_by_type_simulation_atlas_cmp_2016.csv")

cmp.by.type <- cmp.energy %>%
  dplyr::group_by(id.num, usetype, variable) %>%
  dplyr::filter(n() == 2) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(id.num, usetype, variable, source) %>%
  dplyr::filter(variable == "total") %>%
  dplyr::mutate(usage = usage * 1e-9) %>%
  dplyr::filter(usetype %in% c("single_family", "multi_family")) %>%
  dplyr::group_by(usetype) %>%
  dplyr::group_split()

for (df.i in cmp.by.type) {
  type.i = df.i$usetype[[1]]
  print(type.i)
  plot.map.cmp(df.i, "usage", "YlOrRd",
               sprintf("%s building electricity + gas (GBtu)", type.i),
               sprintf("figures/cmp_neighbor_btu_total_%s.png", type.i))
  df.i %>%
    dplyr::filter(variable == "total") %>%
    dplyr::mutate(usage = usage * 1e-9) %>%
    tidyr::spread(source, usage) %>%
    plot.scatter.cmp(sprintf("Electricity + Gas (GBtu) scatter plot\nfor %s building", type.i),
                     sprintf("figures/scatter_neighbor_btu_total_%s.png", type.i))
}
```

Figure 14

```{r figure14, eval=TRUE}
data.2016 <- readr::read_csv("intermediate_data/hourly_heat_energy/annual_2016.csv")
data.2018 <- readr::read_csv("output_data/hourly_heat_energy/annual_2018.csv")

annual.total.2016 <- data.2016 %>%
    dplyr::group_by(geoid) %>%
    dplyr::summarise_if(is.numeric, sum) %>%
    dplyr::ungroup()

annual.total.2018 <- data.2018 %>%
    dplyr::group_by(geoid) %>%
    dplyr::summarise_if(is.numeric, sum) %>%
    dplyr::ungroup()

annual.total.2016 %>%
  dplyr::mutate(year = 2016) %>%
  dplyr::bind_rows(annual.total.2018 %>%
                   dplyr::mutate(year = 2018)) %>%
  dplyr::select(year, geoid, starts_with("energy")) %>%
  tidyr::gather(variable, value, energy.elec:energy.overall) %>%
  dplyr::mutate(value = value * 1e-12) %>%
  dplyr::mutate(year = factor(year)) %>%
  dplyr::mutate_at(vars(variable), recode,
                   "energy.elec" = "electricity",
                   "energy.gas" = "gas",
                   "energy.overall" = "total (electricity + gas)") %>%
  ggplot2::ggplot(ggplot2::aes(x = year, y = value, group = year)) +
  ggplot2::geom_boxplot() +
  ggplot2::facet_wrap(.~variable) +
  ggplot2::ylab("TJ") +
  ggplot2::theme(text = ggplot2::element_text(size = 18))
ggplot2::ggsave(sprintf("figures/cmp_2016_2018_energy_%s.png", grid.level), width=8, height=6, dpi = 600)
```

Figure 15 and 16

```{r figure15and16, eval=TRUE}

## use finer resolution to compare against paper (Zheng & Weng, 2018), as theirs is 120m res
grid.finer <- sf::st_read("output_data/geo_data/finer_grid.geojson")

## city boundary shape
## downloaded from: https://geohub.lacity.org/datasets/city-boundary/explore?location=34.019779%2C-118.412043%2C10.90
city.boundary <- sf::st_read("input_data/domain/City_Boundary.geojson") %>%
  dplyr::select(-OBJECTID)

grid.centroid <- sf::st_centroid(grid.finer)

grid.in.city <- sf::st_join(grid.centroid, city.boundary, join = sf::st_within) %>%
  dplyr::filter(!is.na(CITY)) %>%
  tibble::as_tibble() %>%
  dplyr::select(id.grid.finer, area.m2, FootprintArea.m2)

grid.finer <- grid.finer %>%
  tibble::as_tibble() %>%
  dplyr::select(id.grid.finer, area.m2, FootprintArea.m2)

df.month.hour.avg.per.grid <- readr::read_csv("intermediate_data/diurnal/annual_2018_finer_hourly_avg_month.csv")

df.month.hour.avg.wperm2 <- df.month.hour.avg.per.grid %>%
    dplyr::select(month, Hour, geoid, emission.overall) %>%
    dplyr::left_join(grid.finer, by=c("geoid"="id.grid.finer")) %>%
    dplyr::mutate(emission.overall = emission.overall * 0.000277778 / area.m2) %>%
    dplyr::select(-geoid, -area.m2, -FootprintArea.m2) %>%
    dplyr::group_by(month, Hour) %>%
    dplyr::summarise_if(is.numeric, mean) %>%
    dplyr::ungroup() %>%
    {.}

days = tibble::tibble(month = 1:12,
                      days.in.month = lubridate::days_in_month(as.POSIXct(sprintf("2018-%02d-01", 1:12))))

df.season.avg <- df.month.hour.avg.wperm2 %>%
    dplyr::mutate(month = as.numeric(month)) %>%
    dplyr::mutate(season = case_when(month %in% c(12, 1, 2) ~ "winter",
                                     month %in% c(3, 4, 5) ~ "spring",
                                     month %in% c(6, 7, 8) ~ "summer",
                                     month %in% c(9, 10, 11) ~ "fall")) %>%
    dplyr::left_join(days, by="month") %>%
    dplyr::group_by(season, Hour) %>%
    dplyr::summarise_if(is.numeric, ~weighted.mean(., w = days.in.month)) %>%
    dplyr::ungroup() %>%
    {.}

df.season.avg %>%
    ggplot2::ggplot(ggplot2::aes(x = Hour, y = emission.overall, color = season)) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::ylab("Heat emission (W/m2)") +
    ggplot2::ggtitle("Average hourly total heat emission (W/m2) across finer grids") +
    ggplot2::theme()
ggplot2::ggsave("figures/diurnal_by_season_finer.png", width = 8, height = 4, units = "in", dpi = 600)

df.month.hour.avg.wperm2.by.footprint <- df.month.hour.avg.per.grid %>%
  dplyr::select(month, Hour, geoid, starts_with("emission")) %>%
  dplyr::inner_join(grid.in.city, by=c("geoid"="id.grid.finer")) %>%
  dplyr::select(-area.m2) %>%
  tidyr::gather(variable, value, emission.exfiltration:emission.surf) %>%
  dplyr::mutate(value = value * 0.000277778 / FootprintArea.m2) %>%
  tidyr::spread(variable, value) %>%
  dplyr::group_by(month, Hour) %>%
  dplyr::summarise_if(is.numeric, mean) %>%
  dplyr::ungroup() %>%
  {.}

df.month.hour.avg.wperm2.by.footprint %>%
  dplyr::filter(month == "09") %>%
  dplyr::mutate(emission.no.surf = emission.exfiltration + emission.exhaust + emission.ref + emission.rej) %>%
  ## dplyr::select(month, Hour, emission.no.surf) %>%
  ggplot2::ggplot(ggplot2::aes(x = Hour, y = emission.no.surf)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::expand_limits(y = 0) +
  ggplot2::ggtitle("September diurnal profile for LA city (no surface component)") +
  ggplot2::ylab("Heat emission (W/m2)") +
  ggplot2::theme(text = ggplot2::element_text(size = 16))
ggplot2::ggsave("figures/diurnal_sep_city_div_footprint.png", width = 8, height = 4, units = "in", dpi = 600)
```
