---
title: "Grid level heat emission by building type"
author: "Yujie Xu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/code/im3-wrf/")
```

# Data Preview
```{r readAnnualHeat}
library("dplyr")
library("tmap")

get.spatial.path.suf <- function(spatial.level) {
  if (spatial.level == "coarse") {
    spatial.path = "M02_EnergyPlus_Forcing_Historical_LowRes/meta"
    spatial.suf = ""
  } else if (spatial.level == "finer") {
    spatial.path = "high res grid for reporting"
    spatial.suf = "_finer"
  } else if (spatial.level == "tract") {
    spatial.path = "domain/tl_2018_06_tract"
    ## spatial.path = "domain"
    spatial.suf = "_tract"
  }
  list(spatial.path, spatial.suf)
}

get.grid.size.from.geometry <- function(grid.geo) {
  grid.geo$area.m2 <- sf::st_area(grid.geo)
  grid.no.geo <- grid.geo
  sf::st_geometry(grid.no.geo) <- NULL
  grid.no.geo <- grid.no.geo %>%
    tibble::as_tibble() %>%
    dplyr::mutate(area.m2 = as.numeric(area.m2)) %>%
    dplyr::select(id, area.m2)
  grid.no.geo
}

read.heat.emission.by.type <- function(time.pref, spatial.suf, idf.kw.to.usetype) {
  df <- readr::read_csv(sprintf("%s_heat_by_grid_id_type%s.csv", time.pref, spatial.suf)) %>%
    dplyr::mutate_at(vars(building.type), recode, "small single-family"="single family",
                     "large single-family"="single-family") %>%
    dplyr::left_join(idf.kw.to.usetype, by="idf.kw") %>%
    dplyr::mutate_at(vars(usetype), recode, "res_total"="residential") %>%
    {.}
  df
}

result = get.spatial.path.suf("finer")
spatial.path = result[[1]]
spatial.suf = result[[2]]

grid.geo <- sf::st_read(sprintf("%s/wrf-grids-origin.geojson", spatial.path), quiet=TRUE)

df.area <- get.grid.size.from.geometry(grid.geo)

idf.kw.to.usetype <- readr::read_csv("idf_kw_to_EnergyAtlas_usetype.csv")

df.annual = read.heat.emission.by.type("annual", spatial.suf, idf.kw.to.usetype)
```

Preview of the annual data

```{r annualPreview}
df.annual %>%
  head() %>%
  knitr::kable(caption = "Preview of annual heat emission by type") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", position = "center")
```

```{r getHighestEmissionComponent}
df.annual.long <- df.annual %>%
  dplyr::select(-starts_with("energy")) %>%
  tidyr::gather(variable, value, starts_with("emission")) %>%
  {.}

df.annual.total <- df.annual.long %>%
  dplyr::group_by(id, usetype) %>%
  dplyr::summarise(value = sum(value)) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(df.area, by="id") %>%
  ## convert unit from MJ/m2
  dplyr::mutate(value = value * 1e-6 / area.m2) %>%
  {.}

to.plot.annual.high.emit.comp.type <- df.annual.long %>%
  dplyr::arrange(id, variable, desc(value)) %>%
  dplyr::group_by(id, variable) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(grid.geo, by="id") %>%
  sf::st_as_sf() %>%
  {.}

to.plot.annual.high.emit.type <- df.annual.total %>%
  dplyr::arrange(id, desc(value)) %>%
  dplyr::group_by(id) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(grid.geo, by="id") %>%
  sf::st_as_sf() %>%
  {.}

la.boundary = sf::st_read("domain/la-county-boundary.geojson", quiet=TRUE)
la.boundary.valid = sf::st_make_valid(la.boundary)
```

# Annual

The following shows the building type with the highest heat emission in each grid cell

```{r viewTopEmissionTotal, fig.width=15, fig.height=7, eval=TRUE}
tm_shape(to.plot.annual.high.emit.type) +
  tm_polygons(col="usetype", border.alpha = 0, palette = "Set3") +
  tm_layout(main.title = "Top heat emission building usetype",
            legend.position=c("left", "bottom"), legend.outside=FALSE) +
  tm_shape(la.boundary.valid) +
  tm_polygons("CITY", alpha=0, legend.show=FALSE)
```

The following shows the building type with the highest heat emission for each of the five heat emission component in each grid cell

```{r viewTopEmissionComp, fig.width=15, fig.height=10, eval=TRUE}
tm_shape(to.plot.annual.high.emit.comp.type) +
  tm_polygons(col="usetype", border.alpha = 0, palette = "Set3") +
  tm_facets(by="variable", ncol=3) +
  tm_layout(main.title = "Top heat emission building usetype",
            legend.position=c("left", "bottom"), legend.outside=FALSE) +
  tm_shape(la.boundary.valid) +
  tm_polygons("CITY", alpha=0, legend.show=FALSE)
```

# Monthly

```{r getMonthlyData}
df.monthly = read.heat.emission.by.type("monthly", spatial.suf, idf.kw.to.usetype)

df.monthly.long <- df.monthly %>%
  dplyr::select(-starts_with("energy")) %>%
  tidyr::gather(variable, value, starts_with("emission")) %>%
  {.}

df.monthly.total <- df.monthly.long %>%
  dplyr::group_by(month, id, usetype) %>%
  dplyr::summarise(value = sum(value)) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(df.area, by="id") %>%
  ## convert unit from MJ/m2
  dplyr::mutate(value = value * 1e-6 / area.m2) %>%
  {.}

to.plot.monthly.high.emit.type <- df.monthly.total %>%
  dplyr::arrange(month, id, desc(value)) %>%
  dplyr::group_by(month, id) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(grid.geo, by="id") %>%
  sf::st_as_sf() %>%
  {.}

to.plot.monthly.high.emit.comp.type <- df.monthly.long %>%
  dplyr::arrange(month, id, variable, desc(value)) %>%
  dplyr::group_by(month, id, variable) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(grid.geo, by="id") %>%
  sf::st_as_sf() %>%
  {.}
```

Monthly total heat emission by building use type

```{r viewMonthlyTopEmission, fig.width=15, fig.height=20, eval=TRUE}
tm_shape(to.plot.monthly.high.emit.type) +
  tm_polygons(col="usetype", border.alpha = 0, palette = "Set3") +
  tm_facets(by="month", ncol=3) +
  tm_layout(main.title = "Monthly top heat emission building usetype",
            legend.position=c("left", "bottom"), legend.outside=FALSE) +
  tm_shape(la.boundary.valid) +
  tm_polygons("CITY", alpha=0, legend.show=FALSE)
```

Compare January and July

```{r viewMonthlyTopEmissionJanJul, fig.width=15, fig.height=7, eval=TRUE}
tm_shape(to.plot.monthly.high.emit.type %>% dplyr::filter(month %in% c("01", "07"))) +
  tm_polygons(col="usetype", border.alpha = 0, palette = "Set3") +
  tm_facets(by="month") +
  tm_layout(main.title = "Monthly top heat emission building usetype",
            legend.position=c("left", "bottom"), legend.outside=FALSE) +
  tm_shape(la.boundary.valid) +
  tm_polygons("CITY", alpha=0, legend.show=FALSE)
```

```{r viewMonthlyTopEmissionSurfJanJul, fig.width=15, fig.show="hold", fig.height=7}
heat.source = c("emission.exfiltration", "emission.exhaust", "emission.ref", "emission.rej", "emission.surf")
heat.label = c("exfiltration", "exhaust", "relief air", "HVAC rejection", "building surface")

for (i in seq_along(heat.source)) {
  p <- tm_shape(to.plot.monthly.high.emit.comp.type %>%
           dplyr::filter(month %in% c("01", "07")) %>%
           dplyr::filter(variable == heat.source[[i]])) +
    tm_polygons(col="usetype", border.alpha = 0, palette = "Set3") +
    tm_facets(by="month") +
    tm_layout(main.title = sprintf("Monthly top %s heat emission building usetype", heat.label[[i]]),
              legend.position=c("left", "bottom"), legend.outside=FALSE) +
    tm_shape(la.boundary.valid) +
    tm_polygons("CITY", alpha=0, legend.show=FALSE)
  print(p)
}
```
