---
title: "Annual heat emission from EnergyPlus simulation in 2018"
author: "Yujie Xu"
date: "8/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/code/im3-wrf/")
```
```{r readData, message=FALSE}
library("dplyr")
firstRun = FALSE

df.vin.type.idf <- readr::read_csv("type_vintage_to_idf_mapping.csv") %>%
  dplyr::select(-building.count) %>%
  dplyr::mutate(idf.kw = gsub(".idf", "", idf.name, fixed=TRUE)) %>%
  dplyr::mutate(idf.kw = gsub(".", "_", idf.kw, fixed=TRUE)) %>%
  dplyr::mutate_at(vars(building.type), recode,
                   "small restaurant"="restaurant",
                   "large restaurant"="restaurant",
                   "small retail"="retail",
                   "large retail"="retail",
                   "small single-family"="single-family",
                   "large single-family"="single-family") %>%
  dplyr::distinct() %>%
  {.}

if (firstRun) {

  result <- readr::read_csv("annual_sim_result_by_idf_epw_2018.csv") %>%
      {.}

  format.time <- result %>%
    dplyr::select(-emission.overall, -emission.add.surf, -starts_with("energy")) %>%
    tidyr::separate(`Date/Time`, into=c("Date", "Hour"), sep="  ", remove = FALSE) %>%
    tidyr::separate(`Date`, into=c("month", "day"), sep="/", remove=FALSE) %>%
    dplyr::mutate(`Date` = paste0("2018/", `Date`)) %>%
    dplyr::mutate(date.lubri = lubridate::ymd(`Date`)) %>%
    dplyr::mutate(day.of.week = lubridate::wday(date.lubri, label = TRUE)) %>%
    dplyr::mutate(Hour = as.numeric(gsub(":00:00", "", Hour)) - 1) %>%
    dplyr::mutate(month = as.numeric(month)) %>%
    {.}
  format.time <- format.time %>%
    dplyr::mutate(day = as.numeric(day)) %>%
    dplyr::select(month, day, Hour, day.of.week, idf.kw, epw.id, starts_with("emission"))

  annual.total <- format.time %>%
    dplyr::select(idf.kw, epw.id, starts_with("emission")) %>%
    dplyr::group_by(idf.kw, epw.id) %>%
    dplyr::summarise_if(is.numeric, sum) %>%
    dplyr::ungroup()
  annual.total %>%
    readr::write_csv("annual_2018_total_heat.csv")

  annual.emission.percent.by.component <- annual.total %>%
    tidyr::gather(component, emission.J, starts_with("emission")) %>%
    dplyr::arrange(idf.kw, epw.id) %>%
    dplyr::group_by(idf.kw, epw.id) %>%
    dplyr::mutate(emission.percent = emission.J / sum(emission.J) * 100) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(component = gsub("emission.", "", component, fixed = TRUE)) %>%
    {.}

  idf.to.type.vintage <- annual.emission.percent.by.component %>%
    distinct(idf.kw) %>%
    dplyr::left_join(df.vin.type.idf, by=c("idf.kw")) %>%
    {.}
  to.plot.percent.annual = annual.emission.percent.by.component %>%
    dplyr::left_join(idf.to.type.vintage, by="idf.kw") %>%
    {.}
  to.plot.percent.annual %>%
    readr::write_csv("annual_2018_heat_component.csv")


  monthly.total <- format.time %>%
    dplyr::select(month, idf.kw, epw.id, starts_with("emission")) %>%
    dplyr::group_by(idf.kw, epw.id, month) %>%
    dplyr::summarise_if(is.numeric, sum) %>%
    dplyr::ungroup() %>%
    {.}
  monthly.total %>%
    readr::write_csv("annual_2018_monthly_total_heat.csv")
  monthly.emission.percent.by.component <- monthly.total %>%
    tidyr::gather(component, emission.J, starts_with("emission")) %>%
    dplyr::arrange(idf.kw, epw.id, month) %>%
    dplyr::group_by(idf.kw, epw.id, month) %>%
    dplyr::mutate(emission.percent = emission.J / sum(emission.J) * 100) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(component = gsub("emission.", "", component, fixed = TRUE)) %>%
    {.}

  idf.to.type.vintage <- monthly.emission.percent.by.component %>%
    distinct(idf.kw) %>%
    dplyr::left_join(df.vin.type.idf, by=c("idf.kw")) %>%
    {.}
  to.plot.percent.monthly = monthly.emission.percent.by.component %>%
    dplyr::left_join(idf.to.type.vintage, by="idf.kw") %>%
    {.}
  to.plot.percent.monthly %>%
    readr::write_csv("annual_heat_emission_component_pct_WRF_2018.csv")

  daily.total <- format.time %>%
    dplyr::select(month, day, day.of.week, idf.kw, epw.id, starts_with("emission")) %>%
    dplyr::group_by(idf.kw, epw.id, month, day, day.of.week) %>%
    dplyr::summarise_if(is.numeric, sum) %>%
    dplyr::ungroup() %>%
    {.}
  daily.total %>%
    readr::write_csv("annual_2018_daily_total_heat.csv")

  daily.avg <- daily.total %>%
    dplyr::select(idf.kw, epw.id, starts_with("emission")) %>%
    dplyr::group_by(idf.kw, epw.id) %>%
    dplyr::summarise_if(is.numeric, mean) %>%
    dplyr::ungroup() %>%
    {.}
  daily.avg %>%
    readr::write_csv("annual_2018_daily_avg_heat.csv")

  daily.avg.week.day.weekend <- daily.total %>%
    dplyr::select(day.of.week, idf.kw, epw.id, starts_with("emission")) %>%
    dplyr::mutate(weekday.weekend = ifelse(day.of.week %in% c("Sat", "Sun"), "weekday", "weekend")) %>%
    dplyr::group_by(idf.kw, epw.id, weekday.weekend) %>%
    dplyr::summarise_if(is.numeric, mean) %>%
    dplyr::ungroup() %>%
    {.}
  daily.avg.week.day.weekend %>%
    readr::write_csv("annual_2018_daily_weekday_weekend_avg_heat.csv")

  hourly.avg <- format.time %>%
    dplyr::select(Hour, idf.kw, epw.id, starts_with("emission")) %>%
    dplyr::group_by(idf.kw, epw.id, Hour) %>%
    dplyr::summarise_if(is.numeric, mean) %>%
    dplyr::ungroup() %>%
    {.}
  hourly.avg %>%
    readr::write_csv("annual_2018_hourly_avg_heat.csv")

  hour.day.of.week.avg <- format.time %>%
    dplyr::select(Hour, day.of.week, idf.kw, epw.id, starts_with("emission")) %>%
    dplyr::group_by(idf.kw, epw.id, day.of.week, Hour) %>%
    dplyr::summarise_if(is.numeric, mean) %>%
    dplyr::ungroup() %>%
    {.}
  hour.day.of.week.avg %>%
    readr::write_csv("annual_2018_dayOfWeek_hour_avg_heat.csv")

} else {
  to.plot.percent.annual = readr::read_csv("annual_2018_heat_component.csv")
}
```

The box plot shows the distribution of the percentage of each component in total heat emission.

```{r boxplot, message=FALSE, fig.width = 10, fig.height = 15}
to.plot.percent.annual %>%
  ggplot2::ggplot(ggplot2::aes(x = vintage, y = emission.percent, fill = component)) +
  ggplot2::geom_boxplot() +
  ggplot2::facet_wrap(.~building.type, ncol = 3) +
  ggplot2::theme()
```

The following table shows the average percent of heat emission originated in each of the six sources for each building type vintage combination.

```{r summaryTbl, message=FALSE, warning=FALSE}
to.plot.percent.annual %>%
  dplyr::select(-emission.J) %>%
  dplyr::group_by(idf.kw, building.type, vintage, idf.name, component) %>%
  dplyr::summarise(emission.percent = mean(emission.percent)) %>%
  dplyr::ungroup() %>%
  tidyr::spread(component, emission.percent) %>%
  knitr::kable(caption = "Percent of heat emission for each component", digits = 2) %>%
  kableExtra::collapse_rows()
```


<!-- The following table shows the variable definition -->
```{r variableDef, eval=FALSE}
tibble::tibble(
          `variable` = c("emission.exfiltration", "emission.exhaust", "emission.ref", "emission.rej", "emission.surf"),
          `EnergyPlus output` = c(
            "Environment:Site Total Zone Exfiltration Heat Loss \\[J](Hourly)"
          , "Environment:Site Total Zone Exhaust Air Heat Loss \\[J](Hourly)"
          , "SimHVAC:Air System Relief Air Total Heat Loss Energy \\[J](Hourly)"
          , "SimHVAC:HVAC System Total Heat Rejection Energy \\[J](Hourly)",
            "Environment:Site Total Surface Heat Emission to Air \\[J](Hourly)")
        ) %>%
  knitr::kable(format="html") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

<!-- The following shows for each WRF grid point and building type combination. -->

``` {r plotting, fig.show="hold", fig.width = 10, fig.height = 5, eval=FALSE}
## idf.to.plot = "Warehouse-DOE Ref Pre-1980-ASHRAE 169-2013-3B"
idfs.to.plot <- result %>%
  distinct(idf.kw) %>%
  .$idf.kw

for (idf.to.plot in idfs.to.plot) {
  p <- result %>%
      dplyr::filter(idf.kw == idf.to.plot) %>%
      dplyr::mutate(epw.id = factor(epw.id)) %>%
      dplyr::select(`Date/Time`:epw.id, emission.exfiltration:emission.surf) %>%
      tidyr::gather(variable, value, starts_with("emission")) %>%
      tidyr::separate(`Date/Time`, into=c("Date", "Hour"), sep="  ") %>%
      dplyr::mutate(Hour=as.numeric(gsub(":00:00", "", Hour))) %>%
      dplyr::mutate(Hour = Hour - 1) %>%
      dplyr::mutate(timestamp = as.POSIXct(sprintf("2018/%s %02d:00:00", `Date`, `Hour`))) %>%
      dplyr::filter(as.POSIXct("2018-07-03 12:00:00") < timestamp, timestamp < as.POSIXct("2018-07-16 12:00:00")) %>%
      ggplot2::ggplot(ggplot2::aes(x = timestamp, y = value, color = epw.id, group=interaction(variable, epw.id))) +
      ggplot2::geom_path(size = 0.1) +
      ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-06 00:00:00"), linetype = "dashed") +
      ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-13 00:00:00"), linetype = "dashed") +
      ggplot2::facet_wrap(.~variable, ncol = 2) +
      ggplot2::ggtitle(idf.to.plot) +
      ggplot2::theme()
  print(p)
}
```
