---
title: "Heat emission from EnergyPlus simulation averaged over grid cells"
author: "Yujie Xu"
date: "7/18/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/code/im3-wrf/")
```

```{r readData}
library("dplyr")
library("data.table")

first.run = FALSE
grid.suf = "_finer"
if (first.run) {
  ## fixme: verify whether the read is right
  df <- data.table::fread(sprintf("heat_energy_wrf_grid_time%s.csv", grid.suf))
  to.plot <- df %>%
    tibble::as_tibble() %>%
    dplyr::select(`Date/Time`, variable, kwh.per.footprint.area.m2) %>%
    dplyr::group_by(`Date/Time`, variable) %>%
    dplyr::summarise_if(is.numeric, mean) %>%
    dplyr::ungroup() %>%
    tidyr::separate(`Date/Time`, into=c("Date", "Hour"), sep="  ") %>%
    dplyr::mutate(Hour=as.numeric(gsub(":00:00", "", Hour))) %>%
    dplyr::mutate(Hour = Hour - 1) %>%
    dplyr::mutate(local.time = as.POSIXct(sprintf("2018/%s %s:00:00", `Date`, Hour), tz = "America/Los_Angeles")) %>%
    {.}
  to.plot %>%
    readr::write_csv(sprintf("heat_emission_to_plot%s.csv", grid.suf))
} else {
  to.plot <- readr::read_csv(sprintf("heat_emission_to_plot%s.csv", grid.suf))
}
```

The following are the definition of the variables.

```{r varDef}
tibble::tibble(
          `variable` = c("emission.exh", "emission.ref", "emission.rej", "emission.surf"),
          `EnergyPlus output` = c(
            "Environment:Site Total Zone Exfiltration & Air Heat Loss \\[J](Hourly)"
          , "SimHVAC:Air System Relief Air Total Heat Loss Energy \\[J](Hourly)"
          , "SimHVAC:HVAC System Total Heat Rejection Energy \\[J](Hourly)",
            "Environment:Site Total Surface Heat Emission to Air \\[J](Hourly)")
        ) %>%
  knitr::kable(format="html") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

```{r plotting, fig.width = 14, fig.height = 4}
to.plot %>%
  dplyr::mutate(w.per.footprint.m2 =  kwh.per.footprint.area.m2 * 1000) %>%
  dplyr::filter(!(variable %in% c("emission.overall", "emission.add.surf"))) %>%
  dplyr::filter(!(stringr::str_detect(variable, "energy"))) %>%
  ggplot2::ggplot(ggplot2::aes(x = local.time, y = w.per.footprint.m2, color = variable)) +
  ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-06 00:00:00"), linetype = "dashed") +
  ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-13 00:00:00"), linetype = "dashed") +
  ggplot2::geom_line()
```

```{r plottingNoSurf, fig.width = 14, fig.height = 4}
to.plot %>%
  dplyr::mutate(w.per.footprint.m2 =  kwh.per.footprint.area.m2 * 1000) %>%
  dplyr::filter(!(variable %in% c("emission.overall", "emission.add.surf", "emission.surf"))) %>%
  dplyr::filter(!(stringr::str_detect(variable, "energy"))) %>%
  ggplot2::ggplot(ggplot2::aes(x = local.time, y = w.per.footprint.m2, color = variable)) +
  ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-06 00:00:00"), linetype = "dashed") +
  ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-13 00:00:00"), linetype = "dashed") +
  ggplot2::geom_line()
```
