---
title: "Heat emission from EnergyPlus simulation during a heat wave in 2018"
author: "Yujie Xu"
date: "8/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/code/im3-wrf/")
```
```{r readData, message=FALSE}
library("dplyr")
result <- readr::read_csv("sim_result_by_idf_epw.csv") %>%
    {.}

```

The following table shows the variable definition
```{r variableDef}
tibble::tibble(
          `variable` = c("emission.exfiltration", "emission.exhaust", "emission.ref", "emission.rej", "emission.surf"),
          `EnergyPlus output` = c(
            "Environment:Site Total Zone Exfiltration Heat Loss \\[J](Hourly)"
          , "Environment:Site Total Zone Exhaust Air Heat Loss \\[J](Hourly)"
          , "SimHVAC:Air System Relief Air Total Heat Loss Energy \\[J](Hourly)"
          , "SimHVAC:HVAC System Total Heat Rejection Energy \\[J](Hourly)",
            "Environment:Site Total Surface Heat Emission to Air \\[J](Hourly)")
        ) %>%
  knitr::kable(format="html") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

The following table summarizes the
```{r summaryTbl, message=FALSE}
result %>%
  dplyr::mutate(timestamp = as.POSIXct(sprintf("2018/%s %02d:00:00", `Date`, `Hour`))) %>%
  ## during heat wave
  dplyr::filter(as.POSIXct("2018-07-06 00:00:00") < timestamp, timestamp < as.POSIXct("2018-07-13 00:00:00")) %>%
  tidyr::gather(variable, value, starts_with("emission")) %>%
  {.}
```

The following shows for each WRF grid point and building type combination.

``` {r plotting, fig.show="hold", fig.width = 10, fig.height = 5}
## idf.to.plot = "Warehouse-DOE Ref Pre-1980-ASHRAE 169-2013-3B"
idfs.to.plot <- result %>%
  distinct(idf.kw) %>%
  .$idf.kw

for (idf.to.plot in idfs.to.plot) {
  p <- result %>%
      dplyr::filter(idf.kw == idf.to.plot) %>%
      dplyr::mutate(epw.id = factor(epw.id)) %>%
      dplyr::select(`Date/Time`:epw.id, emission.exfiltration:emission.surf) %>%
      tidyr::gather(variable, value, starts_with("emission")) %>%
      tidyr::separate(`Date/Time`, into=c("Date", "Hour"), sep="  ") %>%
      dplyr::mutate(Hour=as.numeric(gsub(":00:00", "", Hour))) %>%
      dplyr::mutate(Hour = Hour - 1) %>%
      dplyr::mutate(timestamp = as.POSIXct(sprintf("2018/%s %02d:00:00", `Date`, `Hour`))) %>%
      dplyr::filter(as.POSIXct("2018-07-03 12:00:00") < timestamp, timestamp < as.POSIXct("2018-07-16 12:00:00")) %>%
      ggplot2::ggplot(ggplot2::aes(x = timestamp, y = value, color = epw.id, group=interaction(variable, epw.id))) +
      ggplot2::geom_path(size = 0.1) +
      ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-06 00:00:00"), linetype = "dashed") +
      ggplot2::geom_vline(xintercept = as.POSIXct("2018-07-13 00:00:00"), linetype = "dashed") +
      ggplot2::facet_wrap(.~variable, ncol = 2) +
      ggplot2::ggtitle(idf.to.plot) +
      ggplot2::theme()
  print(p)
}
```
