
---
title: "View Grid Cells with High Heat Emission"
author: "Yujie Xu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/code/im3-wrf/")
```

# Top Annual Total Heat Emission Grids
## Top five
```{r viewGridMap, message=FALSE, fig.show="hold"}
library("dplyr")
library("tmap")

separate.lat.lon <- function(df) {
  df %>%
    dplyr::mutate(centroid = as.character(centroid)) %>%
    tidyr::separate(centroid, sep=", ", into=c("lon", "lat")) %>%
    dplyr::mutate(lon = as.numeric(gsub("\\(", "", lon)),
                  lat = as.numeric(gsub("\\)", "", lat))) %>%
    {.}
}

get.plotting.df <- function(filename, df.area.label) {
  sf::st_read(filename) %>%
    dplyr::arrange(desc(emission.wperm2)) %>%
    separate.lat.lon() %>%
    dplyr::left_join(df.area.label, by="id") %>%
    dplyr::mutate(label = sprintf("id = %s<br>Heat emission = %.2f W/m2<br>%s", id, emission.wperm2, area.label)) %>%
    {.}
}

plot.ith.row <- function(top.df, ranking) {
  grid.to.view <- top.df %>%
    dplyr::slice(ranking) %>%
    {.}
  grid.to.view %>%
    leaflet::leaflet() %>%
    leaflet::addPolygons() %>%
    leaflet::addLabelOnlyMarkers(lng = ~lon, lat = ~lat,
                                 label = ~htmltools::HTML(paste("id = ", id,
                                                                "<br>Heat emission = ",
                                                                round(emission.wperm2, 2),
                                                                "W/m2", "<br>Building Footprint Composition<br>",
                                                                area.label)),
                                 labelOptions = leaflet::labelOptions(noHide = TRUE,
                                                                      textOnly = TRUE,
                                                                      style = list(
                                                                        "color" = "white",
                                                                        "font-style" = "bold",
                                                                        "font-size" = "12px",
                                                                        "text-align" = "left"
                                                                      ))
                                 ) %>%
    leaflet::addProviderTiles(providers$Esri.WorldImagery) %>%
    {.}
}

building.info = readr::read_csv("building_info_finer.csv")

idf.kw.to.usetype <- readr::read_csv("idf_kw_to_EnergyAtlas_usetype.csv")

grid.type.area <- building.info %>%
  dplyr::left_join(idf.kw.to.usetype, by="idf.kw") %>%
  dplyr::mutate_at(vars(usetype), recode, "res_total"="residential") %>%
  dplyr::group_by(id, usetype) %>%
  dplyr::summarise_at(vars(building.area.m2, FootprintArea.m2), sum) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(id, desc(FootprintArea.m2)) %>%
  {.}
grid.type.area %>%
  readr::write_csv("finer_grid_4_usetype_area.csv")

grid.area.label <- grid.type.area %>%
  dplyr::select(-building.area.m2) %>%
  dplyr::mutate(area.label = sprintf("%s: %.0f m2", usetype, FootprintArea.m2)) %>%
  dplyr::group_by(id) %>%
  dplyr::summarise(area.label = paste(area.label, collapse = ", ")) %>%
  dplyr::ungroup() %>%
  {.}

## top.k.percent.rej.df <- sf::st_read("high_annual_HVAC_rejection_grids.geojson")
## top.k.percent.surf.df <- sf::st_read("high_annual_surface_heat_grids.geojson") %>%

top.k.percent.df <- get.plotting.df("high_annual_total_heat_grids.geojson", grid.area.label)
plot.ith.row(top.k.percent.df, ranking=1)
plot.ith.row(top.k.percent.df, ranking=2)
plot.ith.row(top.k.percent.df, ranking=3)
plot.ith.row(top.k.percent.df, ranking=4)
plot.ith.row(top.k.percent.df, ranking=5)
```

## Ranking 50 to 55

```{r totalHeat50to55}
plot.ith.row(top.k.percent.df, ranking=51)
plot.ith.row(top.k.percent.df, ranking=52)
plot.ith.row(top.k.percent.df, ranking=53)
plot.ith.row(top.k.percent.df, ranking=54)
plot.ith.row(top.k.percent.df, ranking=55)
```

# Top Annual Total Surface Heat Emission Grids
## Top five
```{r viewGridMapSurf, fig.show="hold"}
top.k.percent.surf.df <- get.plotting.df("high_annual_surface_heat_grids.geojson", grid.area.label)
plot.ith.row(top.k.percent.surf.df, ranking=1)
plot.ith.row(top.k.percent.surf.df, ranking=2)
plot.ith.row(top.k.percent.surf.df, ranking=3)
plot.ith.row(top.k.percent.surf.df, ranking=4)
plot.ith.row(top.k.percent.surf.df, ranking=5)
```

## Rank 50 to 55
```{r totalSurfHeat50to55}
plot.ith.row(top.k.percent.surf.df, ranking=51)
plot.ith.row(top.k.percent.surf.df, ranking=52)
plot.ith.row(top.k.percent.surf.df, ranking=53)
plot.ith.row(top.k.percent.surf.df, ranking=54)
plot.ith.row(top.k.percent.surf.df, ranking=55)
```

# Top Annual Total HVAC Rejection Heat Emission Grids
## Top five
```{r viewGridMapRej, fig.show="hold"}
top.k.percent.rej.df <- get.plotting.df("high_annual_HVAC_rejection_grids.geojson", grid.area.label)
plot.ith.row(top.k.percent.rej.df, ranking=1)
plot.ith.row(top.k.percent.rej.df, ranking=2)
plot.ith.row(top.k.percent.rej.df, ranking=3)
plot.ith.row(top.k.percent.rej.df, ranking=4)
plot.ith.row(top.k.percent.rej.df, ranking=5)
```

## Rank 50 to 55
```{r totalRejHeat50to55}
plot.ith.row(top.k.percent.rej.df, ranking=51)
plot.ith.row(top.k.percent.rej.df, ranking=52)
plot.ith.row(top.k.percent.rej.df, ranking=53)
plot.ith.row(top.k.percent.rej.df, ranking=54)
plot.ith.row(top.k.percent.rej.df, ranking=55)
```
