---
title: "Visualize grid level results"
author: "Yujie Xu"
date: "6/6/2022"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/workLBNL/EESA/code/im3-wrf/rmd")
```
```{r vis, message=FALSE, fig.show="hold", message=FALSE, fig.width=8, fig.height=8}
library("dplyr")

building.heat.grid <- readr::read_csv("../heat_energy_wrf_grid_time.csv")

to.plot <- building.heat.grid %>%
  dplyr::mutate(datetime = as.POSIXct(sprintf("2018/%s", `Date/Time`), format="%Y/%m/%d  %H:%M:%S")) %>%
  dplyr::mutate(day.of.week = lubridate::wday(datetime, label=TRUE),
                hour.of.day = as.numeric(format(datetime, "%H"))) %>%
  dplyr::mutate(is.weekday = !day.of.week %in% c("Sun", "Sat")) %>%
  dplyr::mutate(is.day.time = (8 < hour.of.day) & (hour.of.day < 18)) %>%
  {.}

to.plot %>%
  dplyr::group_by(datetime, variable) %>%
  dplyr::mutate(value = kwh.per.footprint.area.m2) %>%
  dplyr::summarise_at(vars(value),
                      tibble::lst(
                                "10th"=~quantile(., probs=0.1),
                                  "20th"=~quantile(., probs=0.2),
                                  "30th"=~quantile(., probs=0.3),
                                  "40th"=~quantile(., probs=0.4),
                                  "50th"=~quantile(., probs=0.5),
                                  "60th"=~quantile(., probs=0.6),
                                  "70th"=~quantile(., probs=0.7),
                                  "80th"=~quantile(., probs=0.8),
                                  "90th"=~quantile(., probs=0.9)
                                  )) %>%
  dplyr::ungroup() %>%
  tidyr::gather(percentile, value, `10th`:`90th`) %>%
  ## convert to wh per m2
  dplyr::mutate(value = value * 1000) %>%
  dplyr::mutate(variable=factor(variable, levels=c("emission.exh", "emission.ref", "emission.rej", "emission.overall",
                                                   "energy.elec", "energy.gas", "energy.overall"))) %>%
  ggplot2::ggplot(ggplot2::aes(x=datetime, y=value, color=percentile,
                               group=interaction(variable, percentile))) +
  ggplot2::geom_path(size=0.2) +
  ggplot2::ggtitle("Percentile of building emission at wrf grid level") +
  ggplot2::ylab("Wh/m2 building footprint area") +
  ggplot2::scale_color_manual(values=c("#EFF3FF", "#BDD7E7", "#6BAED6",
                                       "#3182BD", "#08519C", "#3182BD",
                                       "#6BAED6", "#BDD7E7", "#EFF3FF")) +
  ggplot2::facet_wrap(.~variable, ncol=2) +
  ggplot2::theme(legend.position = "bottom")
```

```{r vis2, message=FALSE, fig.show="hold", message=FALSE, eval=FALSE}
time.week.day = "07/11  14:00:00"
time.week.night = "07/11  21:00:00"
time.weekend.day = "07/07  14:00:00"
time.weekend.night = "07/07  21:00:00"

la.boundary <- sf::st_read("../domain/la-county-boundary.geojson")

## plot map views

wrf.grid.2 <- sf::st_read("../M02_EnergyPlus_Forcing_Historical_LowRes/meta/wrf-grids-origin.geojson")

days = c("07/11  14:00:00", "07/11  21:00:00", "07/07  14:00:00", "07/07  21:00:00")
labels = c("week_day", "week_night", "weekend_day", "weekend_night")

for (day.idx in seq_along(days)) {
  print(day.idx)
  ## p <- 
  to.plot.i <- to.plot %>%
    dplyr::filter(`Date/Time` == days[[day.idx]]) %>%
    dplyr::left_join(wrf.grid.2, by=c("epw.id"="id")) %>%
    sf::st_as_sf() %>%
    {.}
  to.plot.i %>%
    ggplot2::ggplot() +
    ggplot2::geom_sf(ggplot2::aes(fill=kwh.per.footprint.area.m2)) +
    ggplot2::geom_sf(data=la.boundary, colour = "red",fill=NA) +
    ggplot2::facet_wrap(.~variable) +
    viridis::scale_fill_viridis() +
    ggplot2::ggtitle(sprintf("%s (%s) building emission normalized by footprint kwh/m2",
                             gsub("_", " ", labels[[day.idx]]), days[[day.idx]])) +
    ggplot2::theme(axis.title.x=ggplot2::element_blank(),
                  axis.text.x=ggplot2::element_blank(),
                  axis.ticks.x=ggplot2::element_blank())
  ggplot2::ggsave(sprintf("../images/grid_building_heat_%s.png", labels[[day.idx]]), width=9, height = 7)
  ## print(p)
}

```
